### ISSUE TITLE
Broken build / status

### ISSUE THREAD

**Issue by algermissen** [alexcrichton/tokio-signal#17]
Hi Alex,

Travis indicates a broken build and your last commits seem quite old.

Can you clarify the plans for tokio-signal? I'd look into fixing this, but let me know whether it makes sense at this point.

Jan

**Comment by alexcrichton** [comment]
Thanks for the report! This library is definitely still maintained and receiving bug fixes! It's not all that active because there's not all that much to do (AFAIK). 

I believe the Travis builds are "broken" in the sense that Travis is having a lot of issues as-of-late, but the library still builds and tests just fine.
